version: "2"

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper_container
    ports:
      - "2181:2181"
    environment:
      ZK_TICK_TIME: 2000
      ZK_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "<PRIVATE_IP>:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://<PRIVATE_IP>:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
